### ISSUE TITLE
mock返回数据为Object类型时，与逾期不符

### ISSUE THREAD

**Issue by WDies** [packingjs/packing-template-pug#1]
### mock返回数据为Object类型时，与逾期不符

------test demo-----------

// mock => index.js
`export default (req, res) => { return { me: { [Math.random()]: 1 } }; };`

// template -> index.pug
`script.`
`console.log(!{JSON.stringify(me)});`

// ouput 每刷新页面一次多一个属性
{
0.877618266487793: 1,
0.3259789941366402: 1,
.....
}

#### packing-template-pug 23行代码 assign 方法为 merge 导致数据有误

**Comment by zhongzhi107** [comment]
应该是require导致模块数据缓存了

**Comment by WDies** [comment]
#### packing =>  /lib/middleware.js
const parser = require(`packing-template-${engine}`);
app.get(`/${chunkName}`, parser(options));    // parser() 后 options缓存


#### packing-template-pug
`assign(options, context)`  每执行一次context就会merge到options里面, 如此循环

**Comment by zhongzhi107** [comment]
+ packing-template-pug@2.0.7
